// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF5u4ztG6QCwpYrYaS-zOL_ruuC7c9Erc',
    appId: '1:441446639478:web:a1beee588236c8de147c57',
    messagingSenderId: '441446639478',
    projectId: 'paylist-finance',
    authDomain: 'paylist-finance.firebaseapp.com',
    storageBucket: 'paylist-finance.firebasestorage.app',
    measurementId: 'G-0HGY6FM7EM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiyb5vIJLiOPP4boX_WnTV6frHyAtNL1U',
    appId: '1:441446639478:android:d10938c5cd7af3b1147c57',
    messagingSenderId: '441446639478',
    projectId: 'paylist-finance',
    storageBucket: 'paylist-finance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnoqcL_jes2H-MluKwsRdM8-VOv4su3IM',
    appId: '1:441446639478:ios:ef1dd7311f7ed904147c57',
    messagingSenderId: '441446639478',
    projectId: 'paylist-finance',
    storageBucket: 'paylist-finance.firebasestorage.app',
    iosBundleId: 'br.com.paylist.paylist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnoqcL_jes2H-MluKwsRdM8-VOv4su3IM',
    appId: '1:441446639478:ios:ef1dd7311f7ed904147c57',
    messagingSenderId: '441446639478',
    projectId: 'paylist-finance',
    storageBucket: 'paylist-finance.firebasestorage.app',
    iosBundleId: 'br.com.paylist.paylist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF5u4ztG6QCwpYrYaS-zOL_ruuC7c9Erc',
    appId: '1:441446639478:web:7c46ab15d3b35322147c57',
    messagingSenderId: '441446639478',
    projectId: 'paylist-finance',
    authDomain: 'paylist-finance.firebaseapp.com',
    storageBucket: 'paylist-finance.firebasestorage.app',
    measurementId: 'G-98QYSRXDL3',
  );
}
